# -*- coding: utf-8 -*-
"""spamClassifier_naiveBayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJe1CMeEO8Q4TG6Pv8REICXBUZlNejHH
"""

import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

# Load dataset
df = pd.read_csv(url, sep='\t', header=None, names=['label', 'message'])

print(df.head())

print(df['label'].value_counts())

df['label'] = df['label'].map({'ham': 0, 'spam': 1})

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df['message'], df['label'], test_size=0.2, random_state=42
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

# Fit on training data
X_train_vec = vectorizer.fit_transform(X_train)

# Transform test data
X_test_vec = vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

msg = ["Congratulations! You won a free prize"]

msg_vec = vectorizer.transform(msg)

print("Prediction:", model.predict(msg_vec))

model = MultinomialNB(alpha=0.1)
model.fit(X_train_vec, y_train)

vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2),   # unigrams + bigrams
    min_df=2
)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

